packages:
  - packages/frontend/@n8n/chat

catalog:
  '@types/lodash': ^4.17.17
  '@vitest/coverage-v8': 3.2.4
  lodash: 4.17.21
  uuid: 10.0.0
  vite: ^6.3.5
  vite-plugin-dts: ^4.5.4
  sass: ^1.64.1
  vitest: ^3.1.3
  vitest-mock-extended: ^3.1.0
  unplugin-vue-components: ^0.27.2
  xss: 1.0.15
  typescript: 5.8.3

catalogs:
  frontend:
    '@testing-library/jest-dom': ^6.6.3
    '@testing-library/user-event': ^14.6.1
    '@testing-library/vue': ^8.1.0
    '@vue/tsconfig': ^0.7.0
    '@vueuse/core': ^10.11.0
    '@vitejs/plugin-vue': ^5.2.4
    pinia: ^2.2.4
    unplugin-icons: ^0.19.0
    unplugin-vue-components: ^0.27.2
    vue: ^3.5.13
    vue-i18n: ^11.1.2
    vue-router: ^4.5.0
    vue-tsc: ^2.2.8
    vue-markdown-render: ^2.2.1
    highlight.js: ^11.8.0
    element-plus: 2.4.3
